# Full Dimensionality Reduction Project
# Step 1: Load MNIST Dataset
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Lambda
from tensorflow.keras import backend as K
from tensorflow.keras.losses import mse

# -----------------------------
# Step 1: Load and Preprocess MNIST
# -----------------------------
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28*28) / 255.0
x_test = x_test.reshape(-1, 28*28) / 255.0

print("Training data shape:", x_train.shape)
print("Test data shape:", x_test.shape)

# -----------------------------
# Step 2: PCA
# -----------------------------
pca = PCA(n_components=2)
x_train_pca = pca.fit_transform(x_train)

plt.figure(figsize=(8,6))
scatter = plt.scatter(x_train_pca[:,0], x_train_pca[:,1], c=y_train, cmap='tab10', s=5)
plt.colorbar(scatter, ticks=range(10), label='Digit')
plt.title("MNIST PCA 2D Projection")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

# -----------------------------
# Step 3: Basic Autoencoder
# -----------------------------
input_img = Input(shape=(784,))
encoded = Dense(128, activation='relu')(input_img)
encoded = Dense(64, activation='relu')(encoded)
latent = Dense(32, activation='relu')(encoded)
decoded = Dense(64, activation='relu')(latent)
decoded = Dense(128, activation='relu')(decoded)
output_img = Dense(784, activation='sigmoid')(decoded)

autoencoder = Model(input_img, output_img)
autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(x_train, x_train, epochs=20, batch_size=256, validation_split=0.1)

reconstructed = autoencoder.predict(x_test[:10])
plt.figure(figsize=(10,2))
for i in range(10):
    plt.subplot(2,10,i+1)
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.axis('off')
    plt.subplot(2,10,i+11)
    plt.imshow(reconstructed[i].reshape(28,28), cmap='gray')
    plt.axis('off')
plt.suptitle("Top: Original, Bottom: Autoencoder Reconstructed")
plt.show()

# -----------------------------
# Step 4: Simple 2D Latent Autoencoder (Visual Map)
# -----------------------------
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import matplotlib.pyplot as plt
import numpy as np
# Ensure the data is flattened for the Dense layers
x_train_flat = x_train.reshape(-1, 784)
x_test_flat = x_test.reshape(-1, 784)
# --- 1. Define Model Architecture ---
input_img = Input(shape=(784,))
# Encoder
enc_h = Dense(128, activation='relu')(input_img)
latent = Dense(2, activation='relu')(enc_h)  # The 2D Bottleneck

# Decoder (defined as separate layers for easy reuse)
dec_h_layer = Dense(128, activation='relu')
dec_out_layer = Dense(784, activation='sigmoid')

dec_h = dec_h_layer(latent)
output_img = dec_out_layer(dec_h)

# Full Model
autoencoder_2d = Model(input_img, output_img)
autoencoder_2d.compile(optimizer='adam', loss='mse')

# --- 2. Train ---
print("Training 2D Latent Autoencoder...")
autoencoder_2d.fit(x_train_flat, x_train_flat, epochs=15, batch_size=256, verbose=1)

# --- 3. Visualize the Latent Space ---
encoder_model = Model(input_img, latent)
x_test_latent = encoder_model.predict(x_test_flat)

plt.figure(figsize=(10, 7))
plt.scatter(x_test_latent[:, 0], x_test_latent[:, 1], c=y_test, cmap='tab10', s=2)
plt.colorbar(label='Digit Identity')
plt.title("Task 4: 2D Latent Space Visualization")
plt.xlabel("Latent Dimension 1")
plt.ylabel("Latent Dimension 2")
plt.show()

# --- 4. Generate New Digits (The 'Map' Walk) ---
# Define a standalone decoder model
decoder_input = Input(shape=(2,))
_dec_h = dec_h_layer(decoder_input)
_dec_out = dec_out_layer(_dec_h)
generator_model = Model(decoder_input, _dec_out)

# Pick 10 points along a diagonal in your latent space
# We use the min/max of your actual data to stay within the "learned" area
grid_x = np.linspace(np.min(x_test_latent[:, 0]), np.max(x_test_latent[:, 0]), 10)
grid_y = np.linspace(np.min(x_test_latent[:, 1]), np.max(x_test_latent[:, 1]), 10)

plt.figure(figsize=(15, 3))
for i in range(10):
    # Sample a point: [xi, yi]
    z_sample = np.array([[grid_x[i], grid_y[i]]])
    generated_digit = generator_model.predict(z_sample, verbose=0)

    plt.subplot(1, 10, i + 1)
    plt.imshow(generated_digit.reshape(28, 28), cmap='gray')
    plt.title(f"Pt {i + 1}")
    plt.axis('off')

plt.suptitle("Digits Generated by Walking Through the 2D Latent Map")
plt.show()

# -----------------------------
# Step 5: VQ-VAE Simulation (Improved)
# -----------------------------
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt

# 1. Get latent vectors for a subset of the dataset
x_latent_subset = encoder_model.predict(x_train[:10000])

# 2. Apply KMeans for vector quantization
n_clusters = 32  # more clusters for diversity
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(x_latent_subset)

# 3. Quantize latent vectors (replace each point with its cluster center)
quantized_latent = kmeans.cluster_centers_[kmeans.labels_]

# 4. Add small random noise to each cluster center to simulate variation
noise_scale = 0.05  # small perturbation
quantized_latent_noisy = quantized_latent[:10] + np.random.normal(0, noise_scale, (10,2))

# 5. Decode quantized latent vectors with noise
decoded_quantized_imgs = generator_model.predict(quantized_latent_noisy)

# 6. Plot reconstructed images
plt.figure(figsize=(10,2))
for i in range(10):
    plt.subplot(1,10,i+1)
    plt.imshow(decoded_quantized_imgs[i].reshape(28,28), cmap='gray')
    plt.axis('off')
plt.suptitle("Improved VQ-VAE Simulated Reconstruction with Variation")
plt.show()